//
//  CIPSSEControlBook.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class CIPSSEControlBook: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _fiscalYear: NSNumber?
    var _fiscalMonth: NSNumber?
    
    class func dynamoDBTableName() -> String {

//        return "mytestproject-mobilehub-1216892876-CIP_SSE_ControlBook"
         return "CIP_SSE_ControlBook"
    }
    
    class func hashKeyAttribute() -> String {

        return "_fiscalYear"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_fiscalMonth"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_fiscalYear" : "FiscalYear",
               "_fiscalMonth" : "FiscalMonth",
        ]
    }
}
